//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Opten.Umbraco.Localization Binaries")]
[assembly: AssemblyDescription("Opten.Umbraco.Localization Binaries")]
[assembly: AssemblyCompany("OPTEN AG")]
[assembly: AssemblyProduct("Opten.Umbraco.Localization.Core")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
[assembly: AssemblyCopyright("Copyright © 2015 - 2017 OPTEN AG")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: Guid("a7fc94f6-4d6b-4bfa-af18-f57edaaa39a9")]
[assembly: ComVisible(false)]

