//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitle("Opten.Umbraco.Localization Binaries")]
[assembly: AssemblyDescription("Opten.Umbraco.Localization Binaries")]
[assembly: AssemblyCompany("OPTEN AG")]
[assembly: AssemblyProduct("Opten.Umbraco.Localization.Core")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
[assembly: AssemblyCopyright("Copyright © 2015 - 2017 OPTEN AG")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: Guid("49655439-1a22-415b-9efb-7cb10ca88323")]
[assembly: ComVisible(false)]

[assembly: InternalsVisibleTo("Opten.Umbraco.Localization.Test")]

